on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
name: BuildPush
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: BuildPush
        if: success()
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
          repository: romankrajewski/visense-frontend
          tags: latest